name: Run Setup and Commit Changes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-and-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Run the setup.sh script
      - name: Run Setup Script
        run: |
          chmod +x setup.sh
          ./setup.sh

      # Step 3: Configure Git
      - name: Set Up Git User
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # Step 4: Commit Changes
      - name: Commit Changes
        run: |
          git add .
          git commit -m "Automated setup and changes via GitHub Actions" || echo "No changes to commit"

      # Step 5: Push Changes
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
