name: Run Setup Script and Deploy

on:
  push:
    branches:
      - main

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Ensure Execution Permissions for `setup.sh`
      - name: Make setup.sh Executable
        run: chmod +x setup.sh

      # Step 3: Run setup.sh Script
      - name: Run Setup Script
        run: ./setup.sh

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
